
print('helloooow')

raise Exception('TEst error')